services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: pizza_ordering_system
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysqluserpassword

  db:
    image: mysql:latest
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: pizza_ordering_system
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysqluserpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: